# Generated by Django 4.2.16 on 2024-10-07 11:04

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.TextField(default='', max_length=300, null=True, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='project',
            name='developer',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='개발자'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='git',
            field=models.CharField(default=datetime.datetime(2024, 10, 7, 11, 4, 30, 860471, tzinfo=datetime.timezone.utc), max_length=60, verbose_name='깃허브 주소'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='img_a',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지1'),
        ),
        migrations.AddField(
            model_name='project',
            name='img_b',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지2'),
        ),
        migrations.AddField(
            model_name='project',
            name='img_c',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지3'),
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.CharField(default=datetime.datetime(2024, 10, 7, 11, 4, 34, 803944, tzinfo=datetime.timezone.utc), max_length=40, verbose_name='태그'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='thumnail_img',
            field=models.ImageField(default=datetime.datetime(2024, 10, 7, 11, 4, 37, 748182, tzinfo=datetime.timezone.utc), upload_to='', verbose_name='썸네일 이미지'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='제목'),
        ),
    ]
